### ISSUE TITLE
No deberias dejar las respuestas de los examenes...

### ISSUE THREAD

**Issue by UltiRequiem** [jeyfredc/Curso-de-introduccion-a-Selenium-con-Python#1]
Seria bueno que consideres borrarlo:
https://github.com/jeyfredc/Curso-de-introduccion-a-Selenium-con-Python/blob/master/examen

**Comment by jeyfredc** [comment]
Hola,

no me había dado cuenta de esto, ya lo borre

gracias,

**Comment by UltiRequiem** [comment]
Vale, no hay problema.
